### ISSUE TITLE
Sink Cluster Timeout

### ISSUE THREAD

**Issue by philipz** [GridGain-Demos/gridgain-kafka-replication-demo#1]
Hi,

When I used SQL to check that changes were replicated, the execute is always running. 
Then I found the below error message from gridgain-sink-node container.
Please help!!!

```
class org.apache.ignite.binary.BinaryObjectException: Cannot find metadata for object with compact footer: 630108799
        at org.apache.ignite.internal.binary.BinaryReaderExImpl.getOrCreateSchema(BinaryReaderExImpl.java:2010)
        at org.apache.ignite.internal.binary.BinaryReaderExImpl.<init>(BinaryReaderExImpl.java:285)
        at org.apache.ignite.internal.binary.BinaryReaderExImpl.<init>(BinaryReaderExImpl.java:184)
        at org.apache.ignite.internal.binary.BinaryObjectImpl.reader(BinaryObjectImpl.java:828)
        at org.apache.ignite.internal.binary.BinaryObjectImpl.reader(BinaryObjectImpl.java:842)
        at org.apache.ignite.internal.binary.BinaryObjectImpl.field(BinaryObjectImpl.java:309)
        at org.apache.ignite.internal.processors.query.property.QueryBinaryProperty.fieldValue(QueryBinaryProperty.java:224)
        at org.apache.ignite.internal.processors.query.property.QueryBinaryProperty.value(QueryBinaryProperty.java:119)
        at org.apache.ignite.internal.processors.query.h2.opt.GridH2RowDescriptor.columnValue(GridH2RowDescriptor.java:235)
        at org.apache.ignite.internal.processors.query.h2.opt.H2CacheRow.getValue0(H2CacheRow.java:114)
        at org.apache.ignite.internal.processors.query.h2.opt.H2CacheRow.getValue(H2CacheRow.java:98)
        at org.h2.table.TableFilter.getValue(TableFilter.java:1095)
        at org.h2.expression.ExpressionColumn.getValue(ExpressionColumn.java:215)
        at org.h2.expression.Alias.getValue(Alias.java:37)
        at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1938)
        at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
        at org.h2.result.LazyResult.next(LazyResult.java:60)
        at org.apache.ignite.internal.processors.query.h2.twostep.MapQueryResult.fetchNextPage(MapQueryResult.java:194)
        at org.apache.ignite.internal.processors.query.h2.twostep.GridMapQueryExecutor.prepareNextPage(GridMapQueryExecutor.java:835)
        at org.apache.ignite.internal.processors.query.h2.twostep.GridMapQueryExecutor.onQueryRequest0(GridMapQueryExecutor.java:447)
        at org.apache.ignite.internal.processors.query.h2.twostep.GridMapQueryExecutor.onQueryRequest(GridMapQueryExecutor.java:243)
        at org.apache.ignite.internal.processors.query.h2.IgniteH2Indexing.onMessage(IgniteH2Indexing.java:2183)
        at org.apache.ignite.internal.processors.query.h2.twostep.GridReduceQueryExecutor$1.applyx(GridReduceQueryExecutor.java:149)
        at org.apache.ignite.internal.processors.query.h2.twostep.GridReduceQueryExecutor$1.applyx(GridReduceQueryExecutor.java:144)
```

**Comment by philipz** [comment]
After I cleared Sink two caches, cities and counties, and I executed insert SQL again. This demo can work. But update event isn't work and sync.
